Follow upon cloudwatch formatters
kislyuk/watchtower pull request #138
Opened 2021-01-22 02:28 UTC by terencehonles

This PR brings #117 up to date and addresses the backwards incompatibility mentioned here https://github.com/kislyuk/watchtower/pull/117#issuecomment-711116414

2021-01-22 02:30 UTC, terencehonles commented on watchtower/__init__.py
> +        if self.json_serialize_default and isinstance(message.msg, Mapping):
Dumping JSON will only happen once so it is fine to leave this here instead of removing it.

2021-01-22 19:11 UTC, kislyuk requested changes
This looks good overall, but it needs tests for CloudWatchJSONFormatter. Also, please replace all occurrences of "CloudWatch" with "CloudWatchLog". The former is a different AWS product that is only vaguely related to CWL, so we want to avoid confusion there.

2021-01-22 19:11 UTC, kislyuk commented on watchtower/__init__.py
> +        if self.fields == '__all__':
Please remove the magic value "__all__" and use None as the placeholder for keeping all field values instead.

2021-01-22 19:18 UTC, kislyuk commented
@terencehonles I can add you as a collaborator in this repo if you want CI tests to run correctly (secrets can't be provided to forks). Do you want me to do that?

2021-01-22 22:59 UTC, terencehonles commented
> @terencehonles I can add you as a collaborator in this repo if you want CI tests to run correctly (secrets can't be provided to forks). Do you want me to do that?

Sure that's fine.

2021-01-22 23:03 UTC, terencehonles commented
Actually that might require me to create a new PR since I think that would require this PR come from a branch in this repo. I'm not in a rush for these changes and not sure if it might make sense to check how the credentials are locked down. Not sure if you plan on changing the settings to allow forks once you've done that. If you're not comfortable with that we should probably change the tests to use mocks.

2021-01-30 23:54 UTC, kislyuk commented
@terencehonles are you planning to update this PR for the feedback above? Your changes look good overall, the PR just needs those minor improvements to be merged.

2021-04-30 02:52 UTC, terencehonles commented
I'll try to tend to this when I can. I bumped #144 and made it more useful by actually running mypy (instead of just using it for Sphinx docs), but I'll probably want to try to focus on #139 since I've had to remove this library in order to allow uWSGI to reload gracefully which I hadn't really noticed it wasn't doing until I increased the reload timeout and noticed it was using the full timeout much more often than I would have expected.

2021-11-14 06:40 UTC, kislyuk commented
Thank you for your effort on this PR and for the pointers to formatter best practices. I have implemented the relevant logic in #158 and will release it in v2.0.0. I'm going to close this PR since it is not compatible with some of the changes made in #158.

2021-11-14 06:40 UTC, closed without merging