Truncate messages based on bytes, not unicode characters
kislyuk/watchtower pull request #181
Opened 2023-01-27 22:58 UTC by tomkins

We've been getting this message quite a bit in one of our apps:

```
site-packages/watchtower/__init__.py:339: WatchtowerWarning: Failed to deliver logs: An error occurred (InvalidParameterException) when calling the PutLogEvents operation: Upload too large: 1048681 bytes exceeds limit of 1048576
```

Some of the messages we're sending contain unicode characters, and we're sending a **lot** of messages in the batches. However as the message size calculation is counting the length of strings, instead of the number of bytes - we're getting warnings originating from boto3.

Temporary workaround is to drop the message/batch size - however the better fix is to change the size checking and truncation to look at the bytes of the messages.

2023-01-28 03:22 UTC, kislyuk requested changes
Thanks for your contribution and for chasing down the bug! I just have two minor suggestions, it looks great otherwise.

2023-01-28 03:22 UTC, kislyuk commented on watchtower/__init__.py
> +def _size(msg):
Can you move _size to be a method of CloudWatchLogHandler to simplify customization by subclassing?

2023-01-28 03:22 UTC, kislyuk commented on watchtower/__init__.py
> +def _truncate(msg, max_size):
Same here - Can you move _truncate to be a method of CloudWatchLogHandler to simplify customization by subclassing?

2023-01-28 11:59 UTC, tomkins commented
Updated, and hopefully found an okay place to put them.

Kept them as `_` methods, but can change that back if needed.

2023-01-28 14:32 UTC, merged

2023-01-29 15:34 UTC, kislyuk commented
Released in v3.0.1